---
- name: Executing trusted app
  gather_facts: true
  hosts: localhost
  vars_files: group_vars/vars.yml

  pre_tasks:
  - name: Ensure temp dir in playbook dir
    ansible.builtin.file:
      path: "{{ temp_dir }}"
      state: directory
      mode: '0755'
    tags: always

  - name: Copy facts to file
    ansible.builtin.copy:
      content: "{{ ansible_facts }}"
      dest: "{{ temp_dir }}/facts.json"
      mode: '0755'
    tags: always

  roles:
    - docker
    - mullvad
