---
- name: docker install tasks
  tags: docker_install
  block:
  - name: Print message
    ansible.builtin.debug:
      msg: "installing docker"


- name: docker uninstall tasks
  tags: docker_uninstall
  block:
  - name: Print message
    ansible.builtin.debug:
      msg: "uninstalling docker"
